export const SAGA_WORKSHOPS_APPEND = 'SAGA_WORKSHOPS_APPEND';
export const SAGA_WORKSHOPS_SET = 'SAGA_WORKSHOPS_SET';
export const SAGA_STARTUP_APP = 'SAGA_STARTUP_APP';
export const SAGA_WORKSHOPS_ORDER = 'SAGA_WORKSHOPS_ORDER';
