export const ACTION_WORKSHOP_SET = 'ACTION_WORKSHOP_SET';
export const ACTION_WORKSHOP_APPEND_LIST = 'ACTION_WORKSHOP_APPEND_LIST';
export const ACTION_WORKSHOP_SET_FETCH_STATUS = 'ACTION_WORKSHOP_SET_FETCH_STATUS';
export const ACTION_WORKSHOP_SET_API_PAGE = 'ACTION_WORKSHOP_SET_API_PAGE';
export const ACTION_WORKSHOP_SET_LIMIT_EXCEEDED = 'ACTION_WORKSHOP_SET_LIMIT_EXCEEDED';
export const ACTION_WORKSHOP_RESET = 'ACTION_WORKSHOP_RESET';
export const ACTION_WORKSHOP_SET_ACTIVE_FILTER = 'ACTION_WORKSHOP_SET_ACTIVE_FILTER';
