export const ACTION_WORKSHOP_SET = 'ACTION_WORKSHOP_SET';
export const ACTION_WORKSHOP_APPEND_LIST = 'ACTION_WORKSHOP_APPEND_LIST';
export const ACTION_WORKSHOP_SET_FETCH_STATUS = 'ACTION_WORKSHOP_SET_FETCH_STATUS';
export const ACTION_WORKSHOP_SET_LIMIT_EXCEEDED = 'ACTION_WORKSHOP_SET_LIMIT_EXCEEDED';
export const ACTION_WORKSHOP_RESET = 'ACTION_WORKSHOP_RESET';
export const ACTION_WORKSHOP_SET_ACTIVE_FILTER = 'ACTION_WORKSHOP_SET_ACTIVE_FILTER';

export const ACTION_WORKSHOP_FETCHED = 'ACTION_WORKSHOP_FETCHED';
export const ACTION_WORKSHOP_REQUESTED = 'ACTION_WORKSHOP_REQUESTED';
export const ACTION_WORKSHOP_FAILED = 'ACTION_WORKSHOP_FAILED';
export const ACTION_WORKSHOP_NOT_FOUND = 'ACTION_WORKSHOP_NOT_FOUND';
export const ACTION_WORKSHOP_NO_MORE = 'ACTION_WORKSHOP_NO_MORE';
export const ACTION_WORKSHOP_REQUESTED_MORE = 'ACTION_WORKSHOP_REQUESTED_MORE';

export const ACTION_CART_RESET = 'ACTION_CART_RESET';
export const ACTION_CART_ADD = 'ACTION_CART_ADD';
export const ACTION_CART_UPDATE_QUANTITY = 'ACTION_CART_UPDATE_QUANTITY';
export const ACTION_CART_DELETE = 'ACTION_CART_DELETE';
